apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:8.2.0
    init: confluentinc/confluent-init-container:3.1.1
  dataVolumeCapacity: 100Gi
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
    metricsClient:
      url: http://controlcenter.kafka.svc.cluster.local:9090
  ## TODO MOVE THIS TO FLINK-DEMO OVERLAY
  ## TODO ADD EXPLANATION FOR THIS BLOCK OF CONFIGURATION
  ## USAGE: bootstrap.servers=kafka.flink-demo.confluentdemo.local:31000
  listeners:
    custom:
      - name: external-nodeport
        port: 9094
        externalAccess:
          type: nodePort
          nodePort:
            host: kafka.flink-demo.confluentdemo.local
            nodePortOffset: 31000
        tls:
          enabled: false
